nutrideli_web/main/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for, session
from nutrideli_web.models import Post
from flask_login import login_required, current_user
from nutrideli_web.main.forms import CrearDietaForm
from nutrideli_web import db
from nutrideli_web.ai_model.dieta_modelo import calculate_calories_basic, better_model
from datetime import datetime
import json
import os
from werkzeug.utils import secure_filename
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import load_model
import numpy as np

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/inicio")
def inicio():
    return render_template ('inicio.html', titulo_pagina='Inicio', es_inicio=True)

@main.context_processor
def inject_consejo_del_dia():
    dia_actual = datetime.now().day
    with open('nutrideli_web/static/consejos.json', 'r', encoding='utf-8') as f:
        consejos = json.load(f)
    consejo_del_dia = consejos.get(str(dia_actual))

    return dict(consejo_del_dia=consejo_del_dia)

@main.route("/publicaciones")
def blog_publicaciones():
    page = request.args.get('page', 1, type=int)
    publicaciones = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
    return render_template ('publicaciones.html', publicaciones=publicaciones, titulo_pagina='Publicaciones', es_inicio=False)

@main.route("/nutripedia")
def nutripedia():
    return render_template ('nutripedia.html', titulo_pagina='Nutripedia', es_inicio=False)


@main.route('/buscar_alimento', methods=['POST'])
def buscar_alimento():
    # Obtener el nombre del alimento desde el formulario
    alimento_buscado = request.form['alimento'].capitalize()

    # Cargar el archivo JSON de alimentos
    try:
        with open('nutrideli_web\\static\\alimentos-nutrimentos.json', 'r', encoding='utf-8') as file:
            data = json.load(file)

        # Buscar el alimento en el archivo JSON
        resultado = next((item for item in data['alimentos'] if item['nombre'] == alimento_buscado), None)

        if resultado:
            # Si el alimento se encuentra, mostrar la página con los detalles
            return render_template('nutripedia-res.html', alimento=resultado)
        else:
            # Si el alimento no se encuentra, mostrar un mensaje de error
            flash("El alimento no fue encontrado en la enciclopedia.", 'warning')
            return redirect(url_for('main.nutripedia'))
    
    except FileNotFoundError:
        flash("El archivo de datos no se encuentra.", 'danger')
        return redirect(url_for('main.nutripedia'))

@main.route('/procesar_imagen', methods=['POST'])
def procesar_imagen():
    if 'file' not in request.files:
        flash('No se seleccionó ningún archivo', 'warning')
        return redirect(url_for('main.nutripedia'))

    file = request.files['file']
    
    if file.filename == '':
        flash('No se seleccionó ningún archivo', 'warning')
        return redirect(url_for('main.nutripedia'))

    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        filepath = os.path.join('nutrideli_web\\main\\uploads', filename)
        file.save(filepath)

        # Procesar la imagen con el modelo de IA
        nombre_alimento = procesar_imagen_con_ia(filepath)

        # Redirigir a la barra de búsqueda con el resultado del modelo
        return redirect(url_for('main.buscar_alimento_automatico', alimento=nombre_alimento))

    flash('Formato de archivo no permitido. Solo se permiten JPG y PNG.', 'danger')
    return redirect(url_for('main.nutripedia'))

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in {'jpg', 'jpeg', 'png'}

def procesar_imagen_con_ia(filepath):
    model = tf.keras.models.load_model('nutrideli_web\\main\\Image_classify.keras')

    img_height, img_width = 180, 180
    data_cat = ['ajo', 'berenjena', 'cebolla', 'coliflor', 'espinaca', 'frijoles', 'granada', 'guisantes', 'jalepeno', 'jengibre', 'kiwi', 'lechuga', 'limon', 'maiz', 'maiz dulce', 'mango', 'manzana', 'nabo', 'naranja', 'papa', 'papa culce', 'paprica', 'pepino', 'pera', 'pimiento', 'pimiento morron', 'pimiento picante', 'pina', 'platano', 'rabano', 'remolacha', 'repollo', 'sandia', 'tomate', 'uvas', 'zanahoria']
    
    image = tf.keras.utils.load_img(filepath, target_size=(img_height, img_width))
    img_arr = tf.keras.utils.img_to_array(image)
    img_bat = np.expand_dims(img_arr, 0)

    predict = model.predict(img_bat)

    score = tf.nn.softmax(predict)
    
    nombre_alimento = data_cat[np.argmax(score)]
    
    return nombre_alimento.capitalize()

@main.route('/buscar_alimento_automatico', methods=['GET'])
def buscar_alimento_automatico():
    alimento_buscado = request.args.get('alimento')

    # Cargar el archivo JSON de alimentos (igual que en buscar_alimento)
    try:
        with open('nutrideli_web\\static\\alimentos-nutrimentos.json', 'r', encoding='utf-8') as file:
            data = json.load(file)

        # Buscar el alimento en el archivo JSON
        resultado = next((item for item in data['alimentos'] if item['nombre'] == alimento_buscado), None)

        if resultado:
            return render_template('nutripedia-res.html', alimento=resultado)
        else:
            flash("El alimento no fue encontrado en la enciclopedia.", 'warning')
            return redirect(url_for('main.nutripedia'))
    
    except FileNotFoundError:
        flash("El archivo de datos no se encuentra.", 'danger')
        return redirect(url_for('main.nutripedia'))



@main.route("/acerca_de")
def acerca_de():
    return render_template ('acerca_de.html', titulo_pagina='Acerca de', es_inicio=False)

@main.route("/crear_dieta", methods=['GET', 'POST'])
@login_required
def crear_dieta():
    form = CrearDietaForm()
    if form.validate_on_submit():
        altura = form.altura.data
        peso = form.peso.data
        sexo = form.sexo.data
        objetivo = form.objetivo.data

        calorias = calculate_calories_basic(peso, altura, sexo)
        dieta = better_model(peso, calorias)

        # print(dieta)
        # print(calorias)
        
        # dieta = Dieta(altura=altura, peso=peso, sexo=sexo, objetivo=objetivo, author=current_user)
        # db.session.add(dieta)
        # db.session.commit()

        flash('¡Tu dieta ha sido creada exitosamente!', 'success')
        #return redirect(url_for('main.dieta_creada'))
        return render_template('dieta_creada.html', titulo_pagina='Dieta creada', dieta=dieta, calorias=calorias, es_inicio=False)
    return render_template('crear_dieta.html', titulo_pagina='Crear Dieta', form=form, es_inicio=False)


@main.route("/dieta_creada")
def dieta_creada():
    dieta = session.get('dieta', None)
    if not dieta:
        flash('Por favor, crea una dieta primero.', 'warning')
        return redirect(url_for('main.crear_dieta'))
    return render_template ('dieta_creada.html', titulo_pagina='Dieta creada', dieta=dieta, es_inicio=False)

nutrideli_web/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from nutrideli_web import db
from nutrideli_web.models import Post
from nutrideli_web.posts.forms import Publicacion

posts = Blueprint('posts', __name__)

@posts.route("/publicaciones/nueva", methods=['GET', 'POST'])
@login_required
def nueva_publicacion():
    form = Publicacion()
    if form.validate_on_submit():
         post = Post(title=form.title.data, content=form.content.data, author=current_user)
         db.session.add(post)
         db.session.commit()
         flash('¡Tu publicación ha sido creada!', 'success')
         return redirect(url_for('main.blog_publicaciones'))
    return render_template ('crear_publicacion.html', titulo_pagina='Nueva Publicacion', form=form, legend='¡Comparte tus experiencias con los demás usuarios!', es_inicio=False)


@posts.route("/publicaciones/<int:post_id>")
def post(post_id):
     post = Post.query.get_or_404(post_id)
     return render_template ('publi.html', title=post.title, publicacion=post, es_inicio=False)


@posts.route("/publicaciones/<int:post_id>/modificar", methods=['GET', 'POST'])
@login_required
def modificar_post(post_id):
     post = Post.query.get_or_404(post_id)
     if post.author != current_user:
          abort(403)
     form = Publicacion()
     if form.validate_on_submit():
          post.title = form.title.data
          post.content= form.content.data
          db.session.commit()
          flash('¡Tu publicación ha sido modificada!', 'success')
          return redirect(url_for('posts.post', post_id=post.id))
     elif request.method == 'GET':
          form.title.data = post.title
          form.content.data = post.content
     return render_template ('crear_publicacion.html', titulo_pagina='Modificar Publicacion', form=form, legend='Modificar Publicación', es_inicio=False)


@posts.route("/publicaciones/<int:post_id>/eliminar", methods=['POST'])
@login_required
def eliminar_post(post_id):
     post = Post.query.get_or_404(post_id)
     if post.author != current_user:
          abort(403)
     db.session.delete(post)
     db.session.commit()
     flash('¡Tu publicación ha sido eliminada!', 'success')
     return redirect(url_for('main.blog_publicaciones'))

nutrideli_web/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from nutrideli_web import db, bcrypt
from nutrideli_web.models import User, Post
from nutrideli_web.users.forms import Registro, Iniciar_sesion, Actualizar_informacion, RequestResetForm, ResetPasswordForm
from nutrideli_web.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/registro", methods=['GET', 'POST'])
def registro():
    if current_user.is_authenticated:
         return redirect(url_for('main.inicio'))
    form = Registro()
    if form.validate_on_submit():
                 hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
                 user = User(username=form.username.data, email=form.email.data, password=hashed_password)
                 db.session.add(user)
                 db.session.commit()
                 flash(f'¡Tu cuenta ha sido creada exitosamente, ahora inicia sesión para comenzar a usar NutriDeli!', 'success')
                 return redirect(url_for('users.iniciar_sesion'))
    return render_template ('registro.html', titulo_pagina='Registro', form=form, es_inicio=False)

@users.route("/iniciar_sesion", methods=['GET', 'POST'])
def iniciar_sesion():
    if current_user.is_authenticated:
         return redirect(url_for('main.inicio'))
    form = Iniciar_sesion()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.inicio'))
        else:
            flash('Lo sentimos, no se ha podido iniciar sesión. Compruebe que el correo y la contraseña sean correctos.', 'danger')
    return render_template ('iniciar_sesion.html', titulo_pagina='Iniciar sesión', form=form, es_inicio=False)

@users.route("/cerrar_sesion")
def cerrar_sesion():
     logout_user()
     return redirect(url_for('main.inicio'))


@users.route("/cuenta", methods=['GET', 'POST'])
@login_required
def cuenta():
     form = Actualizar_informacion()
     if form.validate_on_submit():
          if form.picture.data:
               picture_file = save_picture(form.picture.data)
               current_user.image_file = picture_file
          current_user.username = form.username.data
          current_user.email = form.email.data
          db.session.commit()
          flash('¡Tu cuenta ha sido actualizada exitosamente!', 'success')
          return redirect(url_for('users.cuenta'))
     elif request.method == 'GET':
          form.username.data = current_user.username
          form.email.data = current_user.email
     image_file =url_for('static', filename='profile_pics/' + current_user.image_file)
     return render_template ('cuenta.html', titulo_pagina='Cuenta', image_file=image_file, form=form, es_inicio=False)


@users.route("/usuario/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    publicaciones = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
    return render_template ('publicaciones_usuario.html', publicaciones=publicaciones, titulo_pagina='Publicaciones de usuario', user=user, es_inicio=False)


@users.route("/reestablecer_password", methods=['GET', 'POST'])
def reset_request():
     if current_user.is_authenticated:
         return redirect(url_for('main.inicio'))
     form = RequestResetForm()
     if form.validate_on_submit():
          user = User.query.filter_by(email=form.email.data).first()
          send_reset_email(user)
          flash('Un correo con instrucciones se ha enviado a tu correo para reestablecer tu contraseña.', 'info')
          return redirect(url_for('users.iniciar_sesion'))
     return render_template('reestablecer_password.html', title='Reestablecer Password', form=form, es_inicio=False)


@users.route("/reestablecer_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
     if current_user.is_authenticated:
         return redirect(url_for('main.inicio'))
     user = User.verify_reset_token(token)
     if user is None:
          flash('Ese token es inválido o ya ha expirado.', 'warning')
          return redirect(url_for('users.reset_request'))
     form = ResetPasswordForm()
     if form.validate_on_submit():
                 hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
                 user.password = hashed_password
                 db.session.commit()
                 flash(f'¡Tu contraseña ha sido reestablecida exitosamente, ahora inicia sesión para volver a usar NutriDeli!', 'success')
                 return redirect(url_for('users.iniciar_sesion'))
     return render_template('reestablecer_token.html', title='Reestablecer Password', form=form, es_inicio=False)

nutrideli_web/templates/iniciar_sesion.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border=bottom mb-4">¡INICIA SESION EN NUTRIDELI!</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">¿Olvidaste tu contraseña?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            <h4>¿No tienes una cuenta? <a class="ml-2" href="{{ url_for('users.registro') }}">Regístrate</a></h4>
        </small>
    </div>
{% endblock content %}

nutrideli_web/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- ETIQUETAS DE META PARA QUE FUNCIONE BOOTSTRAP -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- BOOTSTRAP CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <title>NutriDeli - {{ titulo_pagina }}</title>
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='useful_images/nutrideli_logoF.png') }}">
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">
              <img src="{{ url_for('static', filename='useful_images/nutrideli_logoF.png') }}" alt="Logo" style="height: 50px;">
              </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <!-- PARTE IZQUIERDA DE LA BARRA DE NAVEGACION -->  
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link {% if request.endpoint == 'main.inicio' %}active{% endif %}" href="{{ url_for('main.inicio') }}">Inicio</a>
                <a class="nav-item nav-link {% if request.endpoint == 'main.blog_publicaciones' %}active{% endif %}" href="{{ url_for('main.blog_publicaciones') }}">Comunideli</a>
                <a class="nav-item nav-link {% if request.endpoint == 'main.crear_dieta' %}active{% endif %}" href="{{ url_for('main.crear_dieta') }}">Dieta</a>
                <a class="nav-item nav-link {% if request.endpoint == 'main.nutripedia' %}active{% endif %}" href="{{ url_for('main.nutripedia') }}">Nutripedia</a>
                <a class="nav-item nav-link {% if request.endpoint == 'main.acerca_de' %}active{% endif %}" href="{{ url_for('main.acerca_de') }}">Acerca de</a>
              </div>
              <!-- PARTE DERECHA DE LA BARRA DE NAVEGACION -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link {% if request.endpoint == 'posts.nueva_publicacion' %}active{% endif %}" href="{{ url_for('posts.nueva_publicacion') }}">Nueva Publicación </a>
                  <a class="nav-item nav-link {% if request.endpoint == 'users.cuenta' %}active{% endif %}" href="{{ url_for('users.cuenta') }}">Cuenta </a>
                  <a class="nav-item nav-link" href="{{ url_for('users.cerrar_sesion') }}">Cerrar sesión</a>
                {% else %}
                  <a class="nav-item nav-link {% if request.endpoint == 'users.iniciar_sesion' %}active{% endif %}" href="{{ url_for('users.iniciar_sesion') }}">Iniciar sesión</a>
                  <a class="nav-item nav-link {% if request.endpoint == 'users.registro' %}active{% endif %}" href="{{ url_for('users.registro') }}">Registrarse</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="{% if not es_inicio %}container{% endif %}">
        <div class="{% if not es_inicio %}row{% endif %}">
          <div class="{% if not es_inicio %}col-md-8{% endif %}">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
          {% if not es_inicio %}
            <div class="col-md-4">
              <div class="content-section">
                <h3 class="text-center">¡Consejo del día!</h3>
                <p class='text-justify'>{{ consejo_del_dia }}</p>
              </div>
            </div>
          {% endif %}
        </div>
    </main>
    <footer class="bg-dark text-white mt-5 p-4 text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <a class="text-white" href="{{ url_for('main.inicio') }}">Inicio</a> |
                    <a class="text-white" href="{{ url_for('main.blog_publicaciones') }}">Comunideli</a> |
                    <a class="text-white" href="{{ url_for('main.crear_dieta') }}">Dieta</a> |
                    <a class="text-white" href="{{ url_for('main.nutripedia') }}">Nutripedia</a> |
                    <a class="text-white" href="{{ url_for('main.acerca_de') }}">Acerca de</a>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <small>&copy; NutriDeli 2024. All Rights Reserved.</small>
                </div>
            </div>
        </div>
    </footer>
    <!-- SCRIPTS DE JAVASCRIPT EN EL ORDEN DE: JQUERY, POPPER.JS Y BOOTSTRAP JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

nutrideli_web/templates/nutripedia.html
{% extends "layout.html" %}
{% block content %}
    <div class="nutripedia-container">
        <!-- Barra de navegación -->
        <nav class="navbar bg-steel-nutri">
            <div class="container d-flex justify-content-between align-items-center">
                <span class="navbar-brand text-nutri">NUTRIPEDIA</span>
                <form class="form-inline" action="{{ url_for('main.buscar_alimento') }}" method="POST">
                    <input class="form-control mr-sm-2" type="search" name="alimento" placeholder="Buscar en la Nutripedia..." aria-label="Search" required>
                    <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Buscar</button>
                </form>
                
            </div>
        </nav>

        <!-- Barra de letras A-Z -->
        <!-- <div class="alphabet-bar">
            <ul class="alphabet-list">
                {% for letter in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' %}
                <li class="alphabet-item"><a href="#">{{ letter }}</a></li>
                {% endfor %}
            </ul>
        </div> -->

        <!-- Imagen e botón -->
        <!-- <div style="text-align: center;">
            <button class="btn btn-info mt-3">Elemento aleatorio de la enciclopedia</button>
        </div> -->


        <article class="media about-section col-md-32">
            <div class="media-body">
                <h1 class="about-title text-center">¿Qué información nutrimental tiene tu alimento de la mesa?</h1>
                <p class="about-content text-justify">Toma una foto de ese alimento, transfierela a tu computadora y súbela en este apartado para darte más información de ese alimento.
                </p>
                <form action="{{ url_for('main.procesar_imagen') }}" method="POST" enctype="multipart/form-data">
                    <label for="file">Sube una imagen de tu alimento:</label>
                    <input type="file" name="file" accept=".jpg,.jpeg,.png" required>
                    <button type="submit" class="btn btn-primary mt-2" style="background-color: #4CAF50; border-color: #4CAF50;">Subir</button>
                </form>
                
            </div>
        </article>

        <div class="random-enciclopedia-section">
            <img src="{{ url_for('static', filename='useful_images/nutripedro.png') }}" alt="Imagen enciclopedia">
        </div>
    </div>
{% endblock content %}


nutrideli_web/templates/publi.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + publicacion.author.image_file) }}">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=publicacion.author.username)}}">{{ publicacion.author.username }}</a>
            <small class="text-muted">{{ publicacion.date_posted.strftime('%d-%m-%Y') }}</small>
            {% if publicacion.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.modificar_post', post_id=publicacion.id)}}">Modificar</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Eliminar</button>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ publicacion.title }}</a></h2>
        <p class="article-content">{{ publicacion.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">¿Está seguro que desea eliminar la publicación?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.eliminar_post', post_id=publicacion.id)}}" method="POST">
                <input class="btn btn-danger" type="submit" value="Eliminar">
            </form>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}

nutrideli_web/templates/publicaciones.html
{% extends "layout.html" %}
{% block content %}
{% for publicacion in publicaciones.items %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + publicacion.author.image_file) }}">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=publicacion.author.username)}}">{{ publicacion.author.username }}</a>
            <small class="text-muted">{{ publicacion.date_posted.strftime('%d-%m-%Y') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=publicacion.id)}}">{{ publicacion.title }}</a></h2>
        <p class="article-content">{{ publicacion.content }}</p>
        </div>
    </article>
{% endfor %}
{% for page_num in publicaciones.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
    {% if page_num %}
        {% if publicaciones.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('main.blog_publicaciones', page=page_num) }}">{{ page_num }}</a>
        {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.blog_publicaciones', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
    {% endif %}
{% endfor %}
{% endblock content %}